### ISSUE TITLE
tailwindcss missing attribute

### ISSUE THREAD

**Issue by Alvazz** [PhilDL/remix-gospel-stack#6]
It looks incomplete, for example I use w-16, but it doesn't actually work. I went to check the generated tailwind.css file, and there is no w-16 item in it, only w-32 item.

**Comment by PhilDL** [comment]
Hello, try tu pull the latest sources, there was a bug with the tailwind watch mode, you had to re-build CSS every-time, I pushed a fix today, please check it out.

**Comment by Alvazz** [comment]
Just re-clone your new version, the problem still exists, in the following button code, try to change w-32 to w-16, you will find that w-16 does not work very well. But w-32 can.


```
<div className="flex w-32 items-center justify-center rounded-md border border-transparent bg-orange-500 px-8 py-3 text-base font-medium text-white no-underline hover:bg-gray-700 dark:bg-white dark:text-black dark:hover:bg-gray-300 md:py-3 md:px-10 md:text-lg md:leading-6">
          From "ui"
          <span className="ml-2 bg-gradient-to-r from-brandred to-brandblue bg-clip-text text-transparent">→</span>
        </div>
```

**Comment by Alvazz** [comment]
This is my modified version based on your template:

https://github.com/Alvazz/streamtaptap-app-web

**Comment by PhilDL** [comment]
Thank you I will take a look as soon as I can.

**Comment by Alvazz** [comment]
Thanks!

**Comment by PhilDL** [comment]
@Alvazz ok I manage to fix it by downgrading tailwindcss, change it in the root package.json

```
"tailwindcss": "3.1.8",
```

then run `pnpm i`

There is a issue linked https://github.com/tailwindlabs/tailwindcss/issues/9667#issuecomment-1295167336

**Comment by Alvazz** [comment]
Going back to 3.1.8 as you said, everything seems to be fine so far. Pending verification, thanks for your help
